### PR TITLE
feat readme and .clang-format

### PR DESCRIPTION
**Pull request by nomad605dis**
Добавил файл претификатора .clang-format и readme.

### CODE REVIEW

**Review by nkrkv — CHANGES_REQUESTED** [review]
This repo is going to be international. So, `README` have to be in English, as well as any content such as code comments

**Comment by nomad605dis** [comment]
Translate `README` to `ENGLISH`.

**Review by nkrkv — CHANGES_REQUESTED** [review]
README proposal:

```markdown
# Amperka Arduino Libraries

This repository contains reusable Arduino libraries made for modules manufactured by [Amperka](https://amperka.com) and general-purpose libraries. It’s a monorepo which hosts multiple libraries at once.

Find the full list under the `libraries/` directory. Details about purpose, installation, and usage can be found in `README.md` files of the corresponding libraries.
```

**Comment by nomad605dis** [comment]
@nkrkv And what is the bad first option?

1. Describe what types of library are available.
2. Description of installing the library in one place.

**Comment by nkrkv** [comment]
> Describe what types of library are available.

There are literally 0 libraries available currently. Make one step at a time.

> Description of installing the library in one place.

Maybe later. Once we’ll see content duplication.

**Pull request closed without merging**
